# Generated by Django 5.1.2 on 2024-12-21 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=100)),
                ('catagory_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='catagory_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Product.productcatagory'),
            preserve_default=False,
        ),
    ]
