# Generated by Django 5.1.2 on 2024-12-21 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_productcatagory_product_catagory_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCatagory',
            new_name='ProductCategory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='catagory_name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='catagory_id',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='catagory_name',
            new_name='category_name',
        ),
    ]
